# User=root
version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    container_name: equipo-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes: 
      - ./data/dump/01.sql:/docker-entrypoint-initdb.d/1.sql
      - ./data/mysql:/var/lib/mysql
    ports: 
      - 3307:3306